//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface ProblemDetails {
    type: string | undefined;
    title: string | undefined;
    status: number | undefined;
    detail: string | undefined;
    instance: string | undefined;

    [key: string]: any;
}

export interface HttpValidationProblemDetails extends ProblemDetails {
    errors: { [key: string]: string[]; };

    [key: string]: any;
}

export interface TransactionCreateDto {
    amount: number;
    type: TransactionType;
    date: Date | undefined;
    description: string | undefined;
}

export enum TransactionType {
    Income = 0,
    Expense = 1,
    Transfer = 2,
}

export interface TransactionUpdateDto {
    description: string | undefined;
    categoryId: string | undefined;
    budgetId: string | undefined;
}

export interface TableDataOfTransactionListItemDto {
    data: TransactionListItemDto[];
    lastPage: number;
}

export interface TransactionListItemDto {
    amount: number;
    type: string;
    date: Date;
}

export interface TransactionDetailsDto {
    amount: number;
    type: string;
    date: Date;
    description: string | undefined;
    category: string | undefined;
    budget: string | undefined;
}

export interface CategoryCreateDto {
    name: string;
    color: string;
}

export interface CategoryUpdateDto {
    name: string;
    color: string;
}

export interface CategoryListItemDto {
    id: string;
    name: string;
    color: string;
}

export interface BudgetCreateDto {
    name: string;
    amount: number;
    startDate: Date;
    endDate: Date;
}

export interface BudgetListItemDto {
    id: string;
    name: string;
    amount: number;
    isValid: boolean;
    expiresIn: number;
    categories: CategoryListItemForBudgetDto[];
}

export interface CategoryListItemForBudgetDto {
    name: string;
    color: string;
}

export interface BudgetDetailsDto {
    name: string;
    amount: number;
    startDate: Date;
    endDate: Date;
}

export interface AuthResultDto {
    token: string;
    tokenExpiration: Date;
    refreshToken: string;
    refreshTokenExpiration: Date;
    username: string;
}

export interface RegisterDto {
    email: string;
    username: string;
    password: string;
}

export interface LoginDto {
    email: string;
    password: string;
}

export interface RefreshTokenDto {
    token: string;
}

export interface Dashboard {
    labels: string[];
    datasets: DashboardDataset[];
}

export interface DashboardDataset {
    label: string;
    data: number[];
}