@HostAddress = https://localhost:7153/api/users
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiNWU4YjE1MjMtZTFlNC00OGJiLTliMDUtMmNjNjg5ZDlkMjA0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiIiwic3ViIjoidGVzdCIsImV4cCI6MTc2ODE1NTMzNiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzE1My8iLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1NjczMy8ifQ.6PIE55qByjvFhO0qZIzbAbuSwdwsJFVXomZnSx2pI04
@Refresh = COeuT5+jZzUidG3NucKGW1Yuvvuz3hyNUqVTZMXZy94=

POST {{HostAddress}}/register
Content-Type: application/json 
{
    "email": "test@test.com",
    "username": "test",
    "password": "Test123_"
}

###

POST {{HostAddress}}/login
Content-Type: application/json 
{
    "email": "test@test.com",
    "password": "Test123_"
}

###

POST {{HostAddress}}/refresh
Content-Type: application/json 
{
    "token": "{{Refresh}}"
}

###

GET {{HostAddress}}/logout
Authorization: Bearer {{Token}}