@HostAddress = https://localhost:7153/api/finance/transactions
@Id = 4F882390-A64C-4A22-ACF6-E984C60A4280
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjVlOGIxNTIzLWUxZTQtNDhiYi05YjA1LTJjYzY4OWQ5ZDIwNCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IiIsInN1YiI6InRlc3QiLCJleHAiOjE3Njc3MTUyOTEsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcxNTMvIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTY3MzMvIn0.Ownyj_NdRpF-Bv5htoOelOn7DGBWIM4JEORrU4HEgIM

GET {{HostAddress}}?index=0&size=10
Authorization: Bearer {{token}}

###

GET {{HostAddress}}/{{Id}}

###

POST {{HostAddress}}
Content-Type: application/json 

{
    "amount": 100,
    "type": 1,
    "date": "2025-12-01"
}
###

PUT {{HostAddress}}/{{Id}}
Content-Type: application/json 

{
    "description": "Huzzah!!!"
}
###
