@HostAddress = https://localhost:7153/api/v1/finance/transactions
@Id = CF15471D-098C-4C8D-AF23-03D0328348DC
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZWM4ZmVkMjktYmYzZS00MzE2LThjZDAtMDhkZTYyOGU5OTJhIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJzdWIiOiJhZG1pbiIsImV4cCI6MTc3MTA4MTk5MiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzE1My8iLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1NjczMy8ifQ.ckXJ-2Ar_P4CcwHG9-Ydwz7q3pE9p2qmQm12JHlTISk

GET {{HostAddress}}?index=0&size=10
Authorization: Bearer {{Token}}

###

GET {{HostAddress}}/{{Id}}
Authorization: Bearer {{Token}}

###

POST {{HostAddress}}
Authorization: Bearer {{Token}}
Content-Type: application/json 

{
    "amount": 100,
    "type": 1,
    "date": "2025-12-01"
}

###

PUT {{HostAddress}}/{{Id}}
Authorization: Bearer {{Token}}
Content-Type: application/json 

{
    "description": "Huzzah!!!"
}

###
