//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface CreateDto {
    amount: number;
    type: TransactionType;
    date: Date | undefined;
    description: string | undefined;
}

export enum TransactionType {
    Income = 0,
    Expense = 1,
    Transfer = 2,
}

export interface UpdateDto {
    description: string | undefined;
    categoryId: string | undefined;
    budgetId: string | undefined;
}

export interface CreateDto2 {
    name: string;
    color: string;
}

export interface UpdateDto2 {
    name: string;
    color: string;
}

export interface CreateDto3 {
    name: string;
    amount: number;
    startDate: Date;
    endDate: Date;
}

export interface RegisterDto {
    email: string;
    username: string;
    password: string;
}

export interface LoginDto {
    email: string;
    password: string;
}

export interface RefreshTokenDto {
    token: string;
}